### ISSUE TITLE
Cropped text on Podcast page on mobile 

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#123]
See https://correlaid-website.vercel.app/podcast on mobile
![Screenshot 2023-04-24 at 10 11 59](https://user-images.githubusercontent.com/67161972/233943228-f1c2e7b3-5f75-4bd2-94e0-9ce0407c7985.png)
#5

**Comment by KonradUdoHannes** [comment]
@jstet I actually also deployed a fix for the underlying issue in the context of the mobile friendliness issue. We had a css issue with our Card component which boiled down to a problem with `line-clamp` in combination with bottom padding and is fixed by using bottom margin instead. Even though podcasts are not using the Card component anymore, I think its probably still good that its fixed in case we use it somewhere else.
