### ISSUE TITLE
Add (end to end) testing to CD action

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#281]
https://github.com/CorrelAid/correlaid_website/blob/main/.github/workflows/cd.yaml will be triggered either manually or periodically by a directus workflow.

**Comment by KonradUdoHannes** [comment]
@jstet I would like to set this up, but need a little more information on how the vercel deployment looks for this/what is needed to integrate it in the vercel deployment. I assume that currently two things happen on vercel site (either directly or indicrectly).

1. npm install
2. npm run build

In order to implement this issue we need the following three steps instead

1. npm install
2. npx playwright install --with-deps
3. npm run build-and-test

What do we need to get there?


Also as a practical issue: In case the build step fails due to something not related to the source code (for instance cms issues). What does it take to simply retry an existing commit, without having to artificially creating a new commit on github.

**Comment by jstet** [comment]
Yes npm install is the install command and npm run build is the build command.

Couldn't we also add the playwright testing to the github action? Maybe we could separate some test into different actions to allow for concurrent execution.  

If doing this with vercels, we could just set `npx playwright install --with-deps && npm run build-and-test` as the build command.

**Comment by jstet** [comment]
we could also include e2e into an action that is triggered when a push to main happens and deactivate the automatic build so that a deploy hook is only called when e2e succeeds. that way prs are possible without e2e suceeding. the same action could be used for triggering a build from the directus ui.

**Comment by KonradUdoHannes** [comment]
That sounds like a good idea to me :+1:.

**Comment by KonradUdoHannes** [comment]
I've added the e2e testing to our CD action in #425 but did not modify the the triggers yet. Manual workflow dispatch worked.

In accordance with the earlier discussion I would suggest to disable vercels automatic builds for `main` and add pr to `main` as a trigger to the workflow, such that all deployments run through the CD workflow. @jstet as I don't have access to the vercel configuration, do we want to coordinate this or do you want to do these last steps?

**Comment by jstet** [comment]
- [ ] Disable Vercel Auto Build

I need to ask @Frie regarding giving you access and dey are on vacation right now

**Comment by jstet** [comment]
Finished implementing this in the pr mentioned above
