### ISSUE TITLE
Podcast page does not show image, no subpages

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#300]
Podcast page still has some issues, some of which i don't know whether they're intentional or not:

- logo is not shown for the entries even though it has 500x500 as requested in the note in directus
- link directly goes to soundcloud --> no subpage for each episode (is this intentional?)

**Comment by KonradUdoHannes** [comment]
#### regarding images

I had a quick look and the reason the images don't appear, is that they are not configured to be loaded right now (which is a simple fix). I tried it out locally and noticed a conceptual issue wrt. the size, i.e. 500x500.

Currently the display for blog posts and podcasts is the same and blog post pictures are designed for a 16:9 aspect ratio. Using a 1:1 ratio therefore leads to a bad fit on the page (image larger then its box).
Do we want to adjust for the display on the website to allow for the 1:1 aspect ratio. Or do we want to adjust the correltak image to the 16:9 aspect ratio (together with the directus note which wants 500x500)

#### regarding subpages

I don't think we had any, at least not since I've been working on it and the commit history did not immediately suggest it either when I had a quick look. Do we need/want subpages here from the content perspective or to keep the user on the site. If desired the episodes themselves could probably be embedded directly on our site, although we would need to check.

**Comment by KonradUdoHannes** [comment]
#306 added the podcast images to fetching and allowed them to card to be high enough for a 1:1 aspect ratio. I already merged this into preview because its probably easier to discuss the desired design if it can be viewed.

@friep what do you think. Shall it stay like this or do we want to size it differently?

**Comment by friep** [comment]
@KonradUdoHannes thanks! 
i uploaded a 16/9 version of the logo and added it to most of the podcasts .. i think i like it better bc otherwise the text is too short for the box.. 

compare here: https://preview.correlaid.pages.dev/podcast/ 
re subpages: that's fine with me.. i was just wondering because we have different links (apple podcast, sppotify...) in directus as well.. so i was wondering how it'd work if we filled those in (right now we only have soundcloud in directus anyway). 

i'll ask the podcast team!

**Comment by jstet** [comment]
I didn't add subpages for the episodes on purpose because I though this is what the Podcast team wanted

**Comment by jstet** [comment]
The soundcloud link is used as the external link

**Comment by jstet** [comment]
we should add external icon #331 in this case

**Comment by friep** [comment]
ok keeping the fields in directus is then the way to go. subpage moved to #341 now. 
I think once you've added the external icon, we can close this issue @jstet .
