### ISSUE TITLE
where can we put photo credits? Maybe to be shown on bottom right of the picture itself?

### ISSUE THREAD

**Issue by IsabelWi** [CorrelAid/correlaid_website#317]

**Comment by friep** [comment]
to clarify: 
this is for images taken from sites like [Unsplash](https://unsplash.com/) but also pictures taken by photographers at our event or different events that we attended. 

Two issues. 

1. where to enter photo credits in directus -> description of image in "Files"? 
2. how to display on website . on the old page we only had this issue for blog posts and i put it below, e.g. here: https://www.correlaid.org/blog/correlaid-strategy-2021/ . but now that we take also hero images, embedding a small overlay onto the picture as @IsabelWi suggests is maybe better? ideally this would be html so that we can include links (see old blog post)

**Comment by jstet** [comment]
> note: also applies to the icons from noun project:
> 
> > You must attribute the artist
> 
> > Insert the link below for digital uses. [More info](https://thenounproject.zendesk.com/hc/en-us/sections/200137528-Icon-Credit-Requirements)

I own a noun project subscription, so I think i can use icons without credit.

**Comment by jstet** [comment]
Re adding this info in the CMS: For Hero images, I would use the description field of the image in directus. For images in WYSIWYG, we can add the "title" attribute to the image in the edit raw option. The latter seems to be a bit hacky (just as adding code) but I dont see an alternative.

**Comment by jstet** [comment]
How to credit authors: https://wiki.creativecommons.org/wiki/best_practices_for_attribution

**Comment by jstet** [comment]
CorrelAid internal images: CorrelAid e.V.,  thenounproject.com CC BY 4.0

**Comment by jstet** [comment]
For thumbmails, e.g. Zeit doesnt add credits. Only on subpage

**Comment by jstet** [comment]
which license would you use alternatively?

**Comment by friep** [comment]
no open license --> no use permitted. Especially for profile pictures, i feel weird putting this under an open license , essentially making people's pictures "stockphotos". if it's just a picture of the CorrelAid cubes, that'd be alright for me. but once people are in /on the picture, i feel it's different. 
see also license in the old website which excluded pictures (which are part of the repo): https://github.com/CorrelAid/hugo-website

**Comment by jstet** [comment]
So you can now add credits via image description to title images, heros, quotes, people and awards.
In WYSIWYG you can add credits via the title attribute

**Comment by friep** [comment]
Reopening because there seems to be an issue on mobile where the credit of the hero overlays into the menu ![image](https://github.com/CorrelAid/correlaid_website/assets/13187448/32ddb4fc-70aa-4527-a3d0-1b16b8a668ed)
![image](https://github.com/CorrelAid/correlaid_website/assets/13187448/e06fea8e-a0be-44b9-95eb-e13de1ae8b9b)
