### ISSUE TITLE
team is not translated

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#325]
global administrators and introductory texts for Remote office and board are not translated on website.

**Comment by KonradUdoHannes** [comment]
I'll check whether this is a cms query issue, and if so should be able to fix it easily. If its missing content I'll document it here and somebody else should pick it up.

**Comment by KonradUdoHannes** [comment]
Fixed by the PR. Also introduced some validation functionality for graphql queries to catch similar issues (the issue was a variable typo).
A similar issue was found on the podcast page, but the impact there was a lot smaller, as the podcasts only exist in German. The only difference seems to be that proper language selection changes the date format of the podcasts.
