### ISSUE TITLE
lowercase citynames in URLs

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#380]
https://correlaid.org/community/correlaidx/berlin is not found, only https://correlaid.org/community/correlaidx/Berlin . for the sake of consistency and easier writing, i think we should lowercase the names in the urls.

**Comment by friep** [comment]
i'd prefer 2. because i think 1. could potentially have unexpected side effects (e.g. when we need the city name in other parts of the site)

**Comment by KonradUdoHannes** [comment]
I deployed the general feature that the lc city names etc. are lowercase in the url, and the internal 

Currently the static page does not feature routes that are differently capitalized, i.e. `Berlin` or `BERLIN` instead of `berlin`. The preview site already features a little bit of this logic, but this does not transfer directly to the static build. Do we also want multiple capitalization options as a feature. If so, I see three options for this.

1. forward in vercel (has the disadvantage of being vercel specific)
2. forward in our service worker (has the disadvantage of making the service worker more complex)
3. build the same static page under several routes (has the disadvantage of using up a bit of redundant disk space because duplicates of the pages would be stored for each route)

**Comment by friep** [comment]
I think all lower case would be sufficient for Isabel and me. this is how it is now on production right? then we can close this issue.
