### ISSUE TITLE
Have to scroll in menu on mobile

### ISSUE THREAD

**Issue by friep** [CorrelAid/correlaid_website#384]
On my iPhone xs, I have to scroll down to see the donate button and the language switcher. I'm not sure people woulddo this intuitively. I'd be bad if we lost English speaking people who can't find the language switcher.

![image](https://github.com/CorrelAid/correlaid_website/assets/13187448/f5709980-9edb-45ed-9b8e-c7db2eff2548)

**Comment by friep** [comment]
I think it's actually visible in the sense that it's on the screen but the safari URL prompt is overlayed?!🥲

**Comment by LtSalt** [comment]
I guess this might be due to using `vh` units - they don't respect mobile boundaries. A fix could be using `dvh` units. Kevin Powell talks about it in [this video](https://youtu.be/veEqYQlfNx8?t=194).

**Comment by KonradUdoHannes** [comment]
Actually with regard to #410 I'm wondering whether we can solve this in general. If a mobile device is in landscape we there will always be scrolling in the menu, because not even the navigation menu fits on it.
 
Maybe we need to address the problem from a different angle. For instance, I think scrolling itself might not even the issue, but that its not clear that there is content/widgets further down below that one can scroll to. Maybe we can find a visual solution for this that makes it more apparent to the user, that he or she can scroll.

**Comment by jstet** [comment]
@LtSalt wrote me on Slack that he has solved this issue

**Comment by LtSalt** [comment]
I just created a pull request. It might be worth the while to check if similar issues exist elsewhere on the website.

**Comment by jstet** [comment]
Looks fine to me, thank you! Lets close this issue then
