### ISSUE TITLE
LC page parsing error

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#578]

**Comment by KonradUdoHannes** [comment]
I'm not sure what the issue here is, but I think generally we have a bit of an issue that the schema is not yet strict enough. I think the old one used to be a little stricter but for the automated inserts I left it a little looser on purpose.
At least I had a few times that all the LC pages where parsing successfully (`npm run build-and-test` completed successfully), but new cms data broke it.

Since we are now near the stage where the majority of the content is present again we should maybe try to tighten the schema whenever such issues arise. This will probably mean to make some fields mandatory for the most part.

**Comment by jstet** [comment]
Moving the filter from Projects_id to Projects in the graphql query solved this, as otherwise projects with null were returned.

**Comment by jstet** [comment]
> Since we are now near the stage where the majority of the content is present again we should maybe try to tighten the schema whenever such issues arise. This will probably mean to make some fields mandatory for the most part.
I suggest opening a new issue for this
