### ISSUE TITLE
Projects Card: Add status and application info

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#741]
![image](https://github.com/CorrelAid/correlaid_website/assets/67161972/30138cbf-640e-4a3c-8fc0-c6e5d7575b10)

@pr130 

I have the some suggestions for the projects db that are kind of related to #621 #636 #664 #739

- we could display project status instead of project type and display project type instead of project data type
- as the goal is to make all projects clickable, replace the cursor icon with some visual hint when a project accepts applications

**Comment by pr130** [comment]
category of organization potentially talk to DSEE first because they started using a categorization in their application forms as well.

**Comment by jstet** [comment]
- Status has priority
- Make everything clickable, remove cursor
- replace cursor with CTA "apply!"

**Comment by pr130** [comment]
I have added a project with a call for applications: https://correlaid.pages.dev/daten-nutzen/projektdatenbank/2024-07-KKV/
status is now still on "Finished" in the CMS plus status = preview. 
at first glance it would make sense to add a field for the application link in directus so that we can place a button above and below the description.

**Comment by jstet** [comment]
#747 first
