### ISSUE TITLE
CorrelAidX Map Attribution collapsed on default

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#81]
Did not manage to do this so far. Looks better on mobile.

**Comment by KonradUdoHannes** [comment]
Maybe we can just run `document.getElementsByClassName('maplibregl-ctrl-attrib-button')[0].click()` (possibly a slightly more robust version) once the particular page has loaded. The question then might be what the appropirate `onload` event is that we have to wait for in order to ensure that the map is already loaded.
